[package]
name = "gen-sugiyama"
description = "Sugiyama algorithm implementation for graph layout"
version = "0.1.29"
edition = "2024"
repository = "https://github.com/genhub-bio/gen"
homepage = "https://genhub.bio"
license = "MIT"

[dependencies]
petgraph = "0.6.5"
log = "0.4.26"

[dev-dependencies]
more-asserts = "0.3.1"
