[package]
name = "gen-annotations"
description = "Annotation models and graph operations for Gen."
version = "0.2.0"
edition = "2024"
repository = "https://github.com/genhub-bio/gen"
homepage = "https://genhub.bio"
license = "Apache-2.0"

[dependencies]
gen-core = { path = "../gen-core", version = "0.2.0" }
gen-graph = { path = "../gen-graph", version = "0.2.0" }
gen-models = { path = "../gen-models", version = "0.2.0" }
interavl = "0.3.0"
noodles = { version = "0.101.0", features = ["bed", "core", "gff"] }
thiserror = "2.0.18"

[dev-dependencies]
rusqlite = { version = "0.32.1", features = ["array", "bundled"] }
tempfile = "3.20.0"
