[package]
name = "gen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
gfa-reader = { git = "https://github.com/MoinSebi/gfa-reader", rev = "9db57c80e34eb137c1d641eabe513101e0de5955" }
include_dir = "0.7.4"
intervaltree = "0.2.7"
itertools = "0.13.0"
rusqlite = { version = "0.31.0", features = ["bundled", "array", "session"] }
rusqlite_migration = { version = "1.2.0" , features = ["from-directory"]}
sha2 = "0.10.8"
tempfile = "3.12.0"
noodles = { version = "0.78.0", features = ["core", "vcf", "fasta", "async"] }
petgraph = "0.6.5"
chrono = "0.4.38"
tempdir = "0.3.7"
