.PHONY: python python-wheel stage-python-client jupyter r r-test release-check-js clean build clippy-fix docker-build gif
python:
	@[ -d .venv ] || python -m venv .venv
	@.venv/bin/pip show maturin >/dev/null 2>&1 || .venv/bin/pip install maturin
	.venv/bin/maturin develop --release --manifest-path gen-python/Cargo.toml --features abi3,extension-module
stage-python-client:
	cargo build --release --locked --bin gen
	mkdir -p gen.gen.data/scripts
	cp target/release/gen gen.gen.data/scripts/gen
	chmod +x gen.gen.data/scripts/gen
python-wheel: stage-python-client
	@[ -d .venv ] || python -m venv .venv
	@.venv/bin/pip show maturin >/dev/null 2>&1 || .venv/bin/pip install maturin
	.venv/bin/maturin build --release --manifest-path gen-python/Cargo.toml --features abi3,extension-module
# The jupyter widget requires a bundled JS file compiled from the TypeScript sources in gen-python/js/.
# We check in the compiled jupyter_widget.js alongside the TS so npm is not required to build the widget.
jupyter: python
	@if command -v npm >/dev/null 2>&1; then \
		cd gen-python && npm install && npm run check && npm run build-jupyter; \
	else \
		echo "npm not found; using committed gen-python/python/gen/static/jupyter_widget.js"; \
		test -f gen-python/python/gen/static/jupyter_widget.js || \
			(echo "Error: gen-python/python/gen/static/jupyter_widget.js missing. Install npm and run 'make jupyter'." && exit 1); \
	fi
	.venv/bin/maturin develop --release --manifest-path gen-python/Cargo.toml --features abi3,extension-module --extras jupyter
r-test:
	# CI only: builds and tests inside Linux Docker container
	@if command -v npm >/dev/null 2>&1; then \
		mkdir -p gen-r/inst/widget && \
		cd gen-python && npm install && npm run build-r; \
	else \
		echo "npm not found; using committed gen-r/inst/widget/genplot.esm.js"; \
		test -f gen-r/inst/widget/genplot.esm.js || \
			(echo "Error: gen-r/inst/widget/genplot.esm.js missing. Install npm and run 'make r'." && exit 1); \
	fi
	DOCKER_BUILDKIT=1 docker build -t gen-r -f ./gen-r/Dockerfile \
		$${GITHUB_PAT:+--secret id=github_pat,env=GITHUB_PAT} . 2>&1 | tail -n 25
	docker run --rm gen-r
r:
	# Builds JS widget and installs natively on the host machine
	@if command -v npm >/dev/null 2>&1; then \
		mkdir -p gen-r/inst/widget && \
		cd gen-python && npm install && npm run build-r; \
	else \
		echo "npm not found; using committed gen-r/inst/widget/genplot.esm.js"; \
		test -f gen-r/inst/widget/genplot.esm.js || \
			(echo "Error: gen-r/inst/widget/genplot.esm.js missing. Install npm and run 'make r'." && exit 1); \
	fi
	Rscript -e "if (!requireNamespace('remotes', quietly=TRUE)) install.packages('remotes'); remotes::install_github('keller-mark/anyhtmlwidget', upgrade='never')"
	# extendr wrappers are generated by calling into the compiled Rust library, so this compiles
	# once to produce R/extendr-wrappers.R, then roxygenise + R CMD INSTALL compile a second time.
	cd gen-r && $(if $(filter Darwin,$(shell uname -s)),MACOSX_DEPLOYMENT_TARGET=11.0) Rscript tools/regenerate-wrappers.R
	Rscript -e "roxygen2::roxygenise('gen-r')"
	$(if $(filter Darwin,$(shell uname -s)),MACOSX_DEPLOYMENT_TARGET=11.0) R CMD INSTALL gen-r
	Rscript -e "for (pkg in c('knitr','rmarkdown')) if (!requireNamespace(pkg, quietly=TRUE)) install.packages(pkg, repos='https://cloud.r-project.org', quiet=TRUE)"
	Rscript -e "tools::buildVignettes(dir='gen-r', tangle=FALSE)"
release-check-js:
	cd gen-python && npm ci && npm run check && npm run build-jupyter
	@echo "Verifying committed jupyter_widget.js/.map match build output..."
	git diff --exit-code gen-python/python/gen/static/jupyter_widget.js gen-python/python/gen/static/jupyter_widget.js.map
clean:
	cargo clean
build:
	cargo build --all-features
clippy-fix:
	cargo +nightly clippy --all-targets --all-features --allow-dirty --allow-staged --fix -- -D clippy::all || cargo +nightly fmt --all
docker-build:
	docker build -t gen .
	docker run -v .:/data --rm --name gen gen cp target/release/gen /data/gen
# Rebuilds every demo repo and re-records its .tape into a .gif alongside it. Each tape's
# directory holds its own build_demo_repo.sh that seeds the /tmp repo the tape records against.
gif:
	cargo build --release --bin gen
	@command -v vhs >/dev/null 2>&1 || (echo "vhs not found; install from https://github.com/charmbracelet/vhs" && exit 1)
	@for tape in $$(find docs -iname '*.tape'); do \
		dir=$$(dirname $$tape); \
		echo "==> $$tape"; \
		if [ -x "$$dir/build_demo_repo.sh" ]; then \
			(cd $$dir && ./build_demo_repo.sh) || exit 1; \
		fi; \
		(cd $$dir && vhs $$(basename $$tape)) || exit 1; \
	done
