[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "gen"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = []
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
description = "Python bindings for the Gen graph database"
readme = "README.md"

[project.optional-dependencies]
jupyter = ["anywidget", "ipywidgets", "traitlets"]

[project.urls]
Repository = "https://github.com/genhub-bio/gen"

[tool.maturin]
manifest-path = "gen-python/Cargo.toml"
features = ["extension-module"]
python-source = "gen-python/python"
module-name = "gen.gen"
