//! Internal support for selectors generated by `ModelSelect`.

use std::collections::BTreeMap;

use itertools::Itertools;
pub use rusqlite::Connection;
use rusqlite::{
    ToSql, params_from_iter,
    types::{ToSqlOutput, Value},
};

use crate::traits::Query;

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum Direction {
    #[default]
    Asc,
    Desc,
    CaseInsensitiveAsc,
    CaseInsensitiveDesc,
}

impl Direction {
    const fn as_sql(self) -> &'static str {
        match self {
            Self::Asc => "ASC",
            Self::Desc => "DESC",
            Self::CaseInsensitiveAsc => "ASC",
            Self::CaseInsensitiveDesc => "DESC",
        }
    }

    const fn uses_case_insensitive_collation(self) -> bool {
        match self {
            Self::Asc | Self::Desc => false,
            Self::CaseInsensitiveAsc | Self::CaseInsensitiveDesc => true,
        }
    }
}

#[doc(hidden)]
pub fn sql_value(value: &impl ToSql) -> Value {
    match value
        .to_sql()
        .expect("should convert selector value to SQL")
    {
        ToSqlOutput::Borrowed(value) => {
            Value::try_from(value).expect("should copy borrowed selector value")
        }
        ToSqlOutput::Owned(value) => value,
        _ => panic!("selector values must map to SQLite scalar values"),
    }
}

#[doc(hidden)]
#[derive(Clone, Debug, PartialEq)]
pub struct SqlFilter {
    pub clause: String,
    pub params: Vec<Value>,
}

impl SqlFilter {
    pub fn new(clause: impl Into<String>, params: Vec<Value>) -> Self {
        Self {
            clause: clause.into(),
            params,
        }
    }
}

#[doc(hidden)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SqlOrder {
    column: String,
    direction: Direction,
}

impl SqlOrder {
    pub fn new(column: impl Into<String>, direction: Direction) -> Self {
        Self {
            column: column.into(),
            direction,
        }
    }
}

#[doc(hidden)]
#[derive(Clone, Copy, Debug)]
pub struct SqlSource {
    table_name: &'static str,
    alias: &'static str,
    source_clause: fn(Option<&str>) -> String,
}

impl SqlSource {
    pub const fn new(
        table_name: &'static str,
        alias: &'static str,
        source_clause: fn(Option<&str>) -> String,
    ) -> Self {
        Self {
            table_name,
            alias,
            source_clause,
        }
    }

    fn clause(self, history_ref: Option<&str>) -> String {
        (self.source_clause)(history_ref)
    }

    pub fn table_name(self) -> &'static str {
        self.table_name
    }

    pub fn alias(self) -> &'static str {
        self.alias
    }
}

#[doc(hidden)]
#[derive(Clone, Debug)]
pub struct SqlJoin {
    source: SqlSource,
    condition: String,
}

impl SqlJoin {
    fn new(source: SqlSource, condition: String) -> Self {
        Self { source, condition }
    }

    fn append_sql(&self, query: &mut String, history_ref: Option<&str>) {
        query.push_str(" JOIN ");
        query.push_str(&self.source.clause(history_ref));
        query.push_str(" ON ");
        query.push_str(&self.condition);
    }

    pub fn source(&self) -> SqlSource {
        self.source
    }
}

#[doc(hidden)]
pub trait SelectQuery {
    fn connection(&self) -> &Connection;

    fn source(&self) -> SqlSource;

    fn history_ref(&self) -> Option<&str>;

    fn joins(&self) -> &[SqlJoin];

    fn filters(&self) -> &[SqlFilter];

    fn order_by(&self) -> &[SqlOrder];

    fn limit(&self) -> Option<u32>;

    fn offset(&self) -> u32;

    fn select_clause(&self) -> String {
        format!("{}.*", self.source().alias())
    }
}

#[doc(hidden)]
pub fn load<M, S>(conn: &Connection, select: &S) -> Vec<M>
where
    M: Query<Model = M>,
    S: SelectQuery,
{
    let mut query = format!(
        "SELECT {} FROM {}",
        select.select_clause(),
        select.source().clause(select.history_ref()),
    );
    for join in select.joins() {
        join.append_sql(&mut query, select.history_ref());
    }

    let mut params = select
        .history_ref()
        .map(|history_ref| vec![Value::from(history_ref.to_string())])
        .unwrap_or_default();
    let filters = select.filters();
    if !filters.is_empty() {
        query.push_str(" WHERE ");
        for (index, filter) in filters.iter().enumerate() {
            if index > 0 {
                query.push_str(" AND ");
            }
            query.push_str(&filter.clause);
            params.extend(filter.params.iter().cloned());
        }
    }

    let order_by = select.order_by();
    if !order_by.is_empty() {
        query.push_str(" ORDER BY ");
        for (index, order) in order_by.iter().enumerate() {
            if index > 0 {
                query.push_str(", ");
            }
            query.push_str(&order.column);
            if order.direction.uses_case_insensitive_collation() {
                query.push_str(" COLLATE NOCASE");
            }
            query.push(' ');
            query.push_str(order.direction.as_sql());
        }
    }

    if let Some(limit) = select.limit() {
        query.push_str(" LIMIT ?");
        params.push(Value::from(i64::from(limit)));
    }
    let offset = select.offset();
    if offset > 0 {
        if select.limit().is_none() {
            query.push_str(" LIMIT -1");
        }
        query.push_str(" OFFSET ?");
        params.push(Value::from(i64::from(offset)));
    }

    let mut statement = conn.prepare(&query).unwrap();
    let rows = statement
        .query_map(params_from_iter(params), |row| Ok(M::process_row(row)))
        .unwrap();
    rows.map(Result::unwrap).collect()
}

#[doc(hidden)]
pub fn qualify_sql_column(alias: &str, column: &str) -> String {
    if column.contains('.') {
        column.to_string()
    } else {
        format!("{alias}.{column}")
    }
}

#[doc(hidden)]
pub fn infer_sql_join(
    conn: &Connection,
    existing_sources: &[SqlSource],
    joined_source: SqlSource,
) -> SqlJoin {
    assert!(
        existing_sources
            .iter()
            .all(|source| source.alias() != joined_source.alias()),
        "cannot join SQL source alias `{}` more than once",
        joined_source.alias(),
    );

    let mut candidates = Vec::new();
    for existing_source in existing_sources {
        for relation in foreign_key_relations(
            conn,
            existing_source.table_name(),
            joined_source.table_name(),
        ) {
            candidates.push(join_condition(
                existing_source.alias(),
                joined_source.alias(),
                &relation,
            ));
        }
        for relation in foreign_key_relations(
            conn,
            joined_source.table_name(),
            existing_source.table_name(),
        ) {
            candidates.push(join_condition(
                joined_source.alias(),
                existing_source.alias(),
                &relation,
            ));
        }
    }

    assert!(
        !candidates.is_empty(),
        "cannot infer a join to `{}`: no direct foreign key connects it to the selected sources",
        joined_source.table_name(),
    );
    assert!(
        candidates.len() == 1,
        "cannot infer a join to `{}`: {} foreign key relationships are possible",
        joined_source.table_name(),
        candidates.len(),
    );

    SqlJoin::new(joined_source, candidates.pop().unwrap())
}

fn foreign_key_relations(
    conn: &Connection,
    source_table: &str,
    target_table: &str,
) -> Vec<Vec<(String, String)>> {
    let query = format!(
        "PRAGMA foreign_key_list({})",
        quote_sql_identifier(source_table),
    );
    let mut statement = conn.prepare(&query).unwrap_or_else(|error| {
        panic!("should inspect foreign keys for `{source_table}`: {error}")
    });
    let rows = statement
        .query_map([], |row| {
            Ok((
                row.get::<_, i64>(0)?,
                row.get::<_, i64>(1)?,
                row.get::<_, String>(2)?,
                row.get::<_, String>(3)?,
                row.get::<_, String>(4)?,
            ))
        })
        .unwrap_or_else(|error| panic!("should query foreign keys for `{source_table}`: {error}"));

    let mut relationships = BTreeMap::<i64, Vec<(i64, String, String)>>::new();
    for row in rows {
        let (id, sequence, referenced_table, source_column, referenced_column) = row
            .unwrap_or_else(|error| {
                panic!("should read foreign keys for `{source_table}`: {error}")
            });
        if referenced_table == target_table {
            relationships
                .entry(id)
                .or_default()
                .push((sequence, source_column, referenced_column));
        }
    }

    relationships
        .into_values()
        .map(|mut columns| {
            columns.sort_by_key(|(sequence, _, _)| *sequence);
            columns
                .into_iter()
                .map(|(_, source_column, referenced_column)| (source_column, referenced_column))
                .collect()
        })
        .collect()
}

fn join_condition(source_alias: &str, target_alias: &str, columns: &[(String, String)]) -> String {
    columns
        .iter()
        .map(|(source_column, target_column)| {
            format!(
                "{source_alias}.{} = {target_alias}.{}",
                quote_sql_identifier(source_column),
                quote_sql_identifier(target_column),
            )
        })
        .join(" AND ")
}

fn quote_sql_identifier(identifier: &str) -> String {
    format!("\"{}\"", identifier.replace('"', "\"\""))
}

#[cfg(test)]
mod tests {
    use super::{SqlSource, infer_sql_join, join_condition};
    use crate::{history::dolt::branch_exists, test_helpers::get_connection};

    const INJECTED_BRANCH: &str = "selector_metadata_injection";

    fn child_source_clause(_history_ref: Option<&str>) -> String {
        "selector_children".to_string()
    }

    fn parent_source_clause(_history_ref: Option<&str>) -> String {
        "selector_parents".to_string()
    }

    #[test]
    fn test_inferred_join_does_not_execute_foreign_key_column_names() {
        let conn = get_connection(None).expect("should create graph database");
        conn.execute_batch(
            r#"
            CREATE TABLE selector_parents (
                id INTEGER PRIMARY KEY
            );
            CREATE TABLE selector_children (
                id INTEGER PRIMARY KEY,
                parent_id INTEGER NOT NULL,
                "parent_id = selector_parents.id AND dolt_branch('selector_metadata_injection') IS NOT NULL --" INTEGER NOT NULL,
                FOREIGN KEY (
                    "parent_id = selector_parents.id AND dolt_branch('selector_metadata_injection') IS NOT NULL --"
                ) REFERENCES selector_parents(id)
            );
            INSERT INTO selector_parents (id) VALUES (1);
            INSERT INTO selector_children (
                id,
                parent_id,
                "parent_id = selector_parents.id AND dolt_branch('selector_metadata_injection') IS NOT NULL --"
            ) VALUES (1, 1, 1);
            "#,
        )
        .expect("should create malicious foreign key schema");
        assert!(
            !branch_exists(&conn, INJECTED_BRANCH).expect("should inspect branches"),
            "test branch should not exist before the inferred join runs",
        );

        let child_source = SqlSource::new(
            "selector_children",
            "selector_children",
            child_source_clause,
        );
        let parent_source =
            SqlSource::new("selector_parents", "selector_parents", parent_source_clause);
        let join = infer_sql_join(&conn, &[child_source], parent_source);
        let query = format!(
            "SELECT COUNT(*) FROM selector_children JOIN selector_parents ON {}",
            join.condition,
        );
        let joined_rows: i64 = conn
            .query_row(&query, [], |row| row.get(0))
            .expect("should execute inferred join");

        assert_eq!(joined_rows, 1, "legitimate foreign key join should work");
        assert!(
            !branch_exists(&conn, INJECTED_BRANCH).expect("should inspect branches"),
            "schema identifiers must never execute as SQL expressions",
        );
    }

    #[test]
    fn test_join_condition_quotes_foreign_key_column_identifiers() {
        let columns = [(
            "source\" OR attacker_effect()".to_string(),
            "target.column".to_string(),
        )];

        assert_eq!(
            join_condition("children", "parents", &columns),
            "children.\"source\"\" OR attacker_effect()\" = parents.\"target.column\"",
        );
    }
}
