[package]
name = "gen-diff"
description = "Diff algorithms for the gen sequence graph and version control system."
version = "0.2.0"
edition = "2024"
repository = "https://github.com/genhub-bio/gen"
homepage = "https://genhub.bio"
license = "Apache-2.0"

[dependencies]
gen-core = { path = "../gen-core", version = "0.2.0" }
gen-graph = { path = "../gen-graph", version = "0.2.0" }
gen-models = { path = "../gen-models", version = "0.2.0" }
itertools = "0.14.0"
petgraph = "0.6.5"
rusqlite = { package = "rusqdoltlite", version = "0.40.4", features = ["fallible_uint"] }
tempfile = "3.24.0"
thiserror = "2.0.12"
