#!/usr/bin/env python3
"""Build the self-contained gen widget JS bundle.

Run this after wasm-pack has built the jupyter-widget crate:

    cd gen-python/jupyter-widget
    wasm-pack build --target web --out-dir pkg

Then from the repo root:

    python gen-python/build_bundle.py

Output: gen-python/python/gen/static/widget.js
  A single ESM module with the WASM binary base64-encoded inline.
  anywidget inlines this as a blob URL — no server extension needed.
"""

import base64
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent
PKG = ROOT / "jupyter-widget" / "pkg"
STATIC = ROOT / "python" / "gen" / "static"
WIDGET_SRC = STATIC / "widget_src.js"
OUTPUT = STATIC / "widget.js"


def main() -> None:
    # Locate wasm-pack output files.
    glue_js = PKG / "jupyter_widget.js"
    wasm_file = PKG / "jupyter_widget_bg.wasm"

    for path in (glue_js, wasm_file, WIDGET_SRC):
        if not path.exists():
            print(f"ERROR: missing {path}", file=sys.stderr)
            print(
                "Run `wasm-pack build --target web --out-dir pkg` in "
                "gen-python/jupyter-widget first.",
                file=sys.stderr,
            )
            sys.exit(1)

    glue = glue_js.read_text()
    wasm_b64 = base64.b64encode(wasm_file.read_bytes()).decode()
    widget_src = WIDGET_SRC.read_text()

    # The wasm-pack --target web glue ends with a re-export line such as:
    #   export { initSync, __wbg_init as default };
    # Strip that line so the bundle has no conflicting default export, then
    # expose __wbg_init under the name __GEN_WASM_INIT__ for widget_src.js.
    glue = re.sub(
        r"^\s*export\s+\{[^}]*__wbg_init\s+as\s+default[^}]*\}\s*;\s*$",
        "",
        glue,
        flags=re.MULTILINE,
    )

    # Build the bundle: glue + WASM bytes constant + widget entry point.
    bundle = f"""\
// AUTO-GENERATED by gen-python/build_bundle.py — do not edit.
// Bundle: jupyter-widget WASM + widget host.

// --- wasm-pack generated glue (jupyter_widget.js) ---
{glue}

// --- WASM binary inlined as base64 ---
const __GEN_WASM_B64__ = "{wasm_b64}";
const __GEN_WASM_BYTES__ = Uint8Array.from(atob(__GEN_WASM_B64__), c => c.charCodeAt(0));

// __wbg_init is the init function from the glue; expose it under the name
// the widget source expects.
const __GEN_WASM_INIT__ = __wbg_init;

// --- widget host (widget_src.js) ---
{widget_src}
"""

    STATIC.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(bundle)

    wasm_kb = wasm_file.stat().st_size // 1024
    bundle_kb = OUTPUT.stat().st_size // 1024
    print(f"✓ {OUTPUT.relative_to(ROOT.parent)}")
    print(f"  WASM: {wasm_kb} KB  →  bundle: {bundle_kb} KB (base64 overhead ~33%)")


if __name__ == "__main__":
    main()
