[package]
name = "gen-python"
description = "Python API for the gen sequence graph and version control system."
version = "0.1.5"
edition = "2024"
repository = "https://github.com/genhub-bio/gen"
homepage = "https://genhub.bio"
license = "Apache-2.0"
publish = false

[lib]
name = "gen_python"
crate-type = ["cdylib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
flate2 = "1.1.5"
gen = { path = ".." }
gen-core = { path = "../gen-core", features = ["python-bindings"] }
gen-graph = { path = "../gen-graph" }
gen-models = { path = "../gen-models" }
log = "0.4.26"
rusqlite = { version = "0.32.1", features = ["bundled", "array", "limits", "session"] }

[dependencies.pyo3]
version = "0.25.1"
features = []

[build-dependencies]
pyo3-build-config = "0.26.0"

[workspace]
members = ["."]
