//! Minimal, hand-written `#[repr(C)]` bindings to the subset of Emscripten's synchronous Fetch
//! API (`emscripten/fetch.h`) needed by [`super::browser_http`].
//!
//! Provenance: generated by hand (no `bindgen`/`libclang` available in this environment) against
//! the header shipped with the pinned Emscripten SDK version this workspace builds with (`4.0.9`,
//! see the `wasm` target in `Makefile`), read from:
//!
//! ```text
//! $EMSDK_DIR/upstream/emscripten/cache/sysroot/include/emscripten/fetch.h
//! ```
//!
//! Every field below was checked against that header one at a time: name (converted to
//! `snake_case`), declaration order (required for `#[repr(C)]` to match the C layout), and type
//! (`char[N]` -> fixed-size `[c_char; N]` inline buffer, not a pointer; `size_t` -> `usize`;
//! `uint32_t`/`uint64_t`/`unsigned short` -> the matching fixed-width Rust integer; `bool` ->
//! `bool`, both single-byte on this target; pointer and function-pointer fields -> raw pointers /
//! `Option<extern "C" fn(...)>`). Only the functions and constants synchronous, in-memory,
//! header-and-body requests need are declared; `emscripten_fetch_wait` (deprecated) and the
//! response-header-string helpers are intentionally omitted.
//!
//! If the pinned Emscripten SDK version in `Makefile` ever changes, re-diff this file against the
//! new `fetch.h` before relying on it again.

use core::ffi::{c_char, c_void};

/// If passed, the body of the request will be present in full in the `onsuccess()` handler.
pub const EMSCRIPTEN_FETCH_LOAD_TO_MEMORY: u32 = 1;
/// Skips the implicit IndexedDB cache lookup/store that runs when none of
/// `APPEND`/`REPLACE`/`NO_DOWNLOAD` is set (see `fetch.h`'s comment on `EMSCRIPTEN_FETCH_APPEND`).
/// That lookup is asynchronous regardless of `EMSCRIPTEN_FETCH_SYNCHRONOUS` -- without this flag,
/// `emscripten_fetch()` returns a still-zeroed struct before the real request ever runs. Required
/// for a synchronous, in-memory-only request that neither reads nor writes IndexedDB.
pub const EMSCRIPTEN_FETCH_REPLACE: u32 = 16;
/// If passed, `emscripten_fetch()` runs synchronously to completion before returning.
pub const EMSCRIPTEN_FETCH_SYNCHRONOUS: u32 = 64;

/// `#define EMSCRIPTEN_RESULT int` (see `emscripten/em_types.h`); `0` is
/// `EMSCRIPTEN_RESULT_SUCCESS`.
pub type EmscriptenResult = i32;

/// Mirrors `emscripten_fetch_attr_t`. Field order matches the C declaration exactly, which is
/// what makes `#[repr(C)]` produce the same layout the Emscripten runtime expects.
#[repr(C)]
pub struct EmscriptenFetchAttr {
    pub request_method: [c_char; 32],
    pub user_data: *mut c_void,
    pub onsuccess: Option<extern "C" fn(*mut EmscriptenFetch)>,
    pub onerror: Option<extern "C" fn(*mut EmscriptenFetch)>,
    pub onprogress: Option<extern "C" fn(*mut EmscriptenFetch)>,
    pub onreadystatechange: Option<extern "C" fn(*mut EmscriptenFetch)>,
    pub attributes: u32,
    pub timeout_milliseconds: u32,
    pub with_credentials: bool,
    pub destination_path: *const c_char,
    pub user_name: *const c_char,
    pub password: *const c_char,
    pub request_headers: *const *const c_char,
    pub overridden_mime_type: *const c_char,
    pub request_data: *const c_char,
    pub request_data_size: usize,
}

/// Mirrors `emscripten_fetch_t`. Field order matches the C declaration exactly, including the
/// trailing `__attributes` field the header documents as "for internal use only" -- it must stay
/// present so this struct's size and the offsets the runtime uses for earlier fields line up.
#[repr(C)]
pub struct EmscriptenFetch {
    pub id: u32,
    pub user_data: *mut c_void,
    pub url: *const c_char,
    pub data: *const c_char,
    pub num_bytes: u64,
    pub data_offset: u64,
    pub total_bytes: u64,
    pub ready_state: u16,
    pub status: u16,
    pub status_text: [c_char; 64],
    pub __attributes: EmscriptenFetchAttr,
}

unsafe extern "C" {
    /// Clears the fields of an `emscripten_fetch_attr_t` to their default values.
    pub fn emscripten_fetch_attr_init(fetch_attr: *mut EmscriptenFetchAttr);

    /// Initiates a new Emscripten fetch operation. With `EMSCRIPTEN_FETCH_SYNCHRONOUS` set, runs
    /// to completion and returns a non-null pointer, or null if the operation could not even be
    /// started (e.g. invalid parameters).
    pub fn emscripten_fetch(
        fetch_attr: *mut EmscriptenFetchAttr,
        url: *const c_char,
    ) -> *mut EmscriptenFetch;

    /// Closes a finished or executing fetch operation and frees all memory associated with it,
    /// including the `data` buffer. Must be called exactly once per non-null `emscripten_fetch`
    /// return value.
    pub fn emscripten_fetch_close(fetch: *mut EmscriptenFetch) -> EmscriptenResult;
}
