name: R Package Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  docker-install-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build Docker install test image
        run: |
          docker build -f gen-r/Dockerfile -t gen-r-install-test .
          docker run --rm gen-r-install-test
