name: R Package Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  docker-install-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Build Docker install test image
        env:
          GITHUB_PAT: ${{ secrets.MINIMAL_RO_PAT }}
        run: |
          DOCKER_BUILDKIT=1 docker build -f gen-r/Dockerfile --secret id=github_pat,env=GITHUB_PAT -t gen-r-install-test .
          docker run --rm gen-r-install-test
