name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo llvm-cov --html --no-fail-fast
      continue-on-error: true

    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: target/llvm-cov/html/*
        overwrite: true
