name: Test Python Bindings

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install capnproto
      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install capnproto
      - name: Test
        working-directory: gen-python
        run: cargo test
