name: Versioned Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: choice
        description: 'The semver bump level'
        options:
          - 'patch'
          - 'minor'
          - 'major'
        default: 'patch'
jobs:
  versioned-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump cargo version
        id: bump-cargo-version
        uses: tj-actions/cargo-bump@v3
      - name: Commit cargo version bump and apply tag and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
	  echo "Dry run: would bump version from ${{ steps.bump-cargo-version.outputs.old_version }} to ${{ steps.bump-cargo-version.outputs.new_version }}."
#          git add Cargo.toml Cargo.lock
#          git commit -m "Bump version"
#          git push
#          git tag -a "${{ steps.bump-cargo-version.outputs.new_version }}" -m "Release: ${{ steps.bump-cargo-version.outputs.new_version }}"
#          git push origin "${{ steps.bump-cargo-version.outputs.new_version }}"
