name: Versioned Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: choice
        description: 'The semver bump level'
        options:
          - 'patch'
          - 'minor'
          - 'major'
        default: 'patch'

jobs:
  versioned-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Bump cargo version
      id: bump-cargo-version
      uses: tj-actions/cargo-bump@v3
    - name: Commit cargo version bump, apply git tag, push
      run: |
        echo "Bumping version from ${{ steps.bump-cargo-version.outputs.old_version }} to ${{ steps.bump-cargo-version.outputs.new_version }}."
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Cargo.toml Cargo.lock
        git commit -m "Bump version"
        git push
        git tag -a "${{ steps.bump-cargo-version.outputs.new_version }}" -m "Release: ${{ steps.bump-cargo-version.outputs.new_version }}"
        git push origin "${{ steps.bump-cargo-version.outputs.new_version }}"
        echo "Version updated and tag created."
    - name: Generate release tarball
      run: git archive --format=tar.gz -o "gen-${{ steps.bump-cargo-version.outputs.new_version }}.tar.gz" --prefix=gen/ main
    - name: Upload release tarball
      uses: actions/upload-artifact@v4
      with:
        name: gen-release-tarball
        path: "gen-${{ steps.bump-cargo-version.outputs.new_version }}.tar.gz"
